name: binaryninja-haskell
version: 0.1
synopsis: Bindings for binaryninja api
bug-reports: https://github.com/loganleland/binaryninja-haskell/issues
homepage: https://github.com/loganleland/binaryninja-haskell
category: FFI
license: MIT
author: Logan Leland
maintainer: logan@leland.zip
stability: alpha
tested-with:
  GHC==9.12

description: Bindings for binaryninja api

extra-source-files:
- README.md
dependencies:
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- text

library:
  source-dirs: src
  exposed-modules:
    Binja.BinaryView
    Binja.FFI
    Binja.Llil
    Binja.Mlil
    Binja.Function
    Binja.Plugin
    Binja.ReferenceSource
    Binja.Symbol
    Binja.Types
    Binja.Utils
  other-modules: []
  ghc-options:
    - -Wall
    - -threaded
  ld-options:
    - -Wl,-rpath,${pkgroot} # for macOS
    - -Wl,-rpath,. # for macOS
  c-sources:
    - cbits/wrapper.c
  include-dirs:
    - cbits
  extra-libraries:
    - binaryninjacore

executables:
  example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -Wall
      - -threaded
    ld-options:
      - -Wl,-rpath,${pkgroot} # for macOS
      - -Wl,-rpath,. # for macOS
    extra-libraries:
      - binaryninjacore
    dependencies:
      - binaryninja-haskell

